export const lable = {
  required: "Required",
  severity: {
    error: "error",
    success: "success",
  },
  dashboard: {
    appName: "Zoi Cart",
    welcome: "Welcome back, {name}!",
    dashboardOverview: "Here's what's happening with your store today.",
    shopByCategory: "Shop by Category",
    viewAllCategories: "View All Categories",
    todaysSpecialOffers: "Today's Special Offers",
    viewAllOffers: "View All",
    featuredProducts: "Featured Products",
    featured: "Featured",
    shopNow: "Shop Now",
    addToCart: "Add to Cart",
    confirmLogout: {
      title: "Confirm Logout",
      message: "Are you sure you want to logout?",
      cancel: "Cancel",
      logout: "Logout",
    },
    menuItems: {
      dashboard: "Dashboard",
      products: "Products",
      orders: "Orders",
      customers: "Customers",
      settings: "Settings",
      logout: "Logout",
      profile: "Profile",
    },
    notifications: {
      title: "Notifications",
      newOrder: "New order received",
      paymentProcessed: "Payment processed",
      newCustomer: "New customer registered",
    },
  },
  common: {
    required: "Required",
    severity: {
      error: "error",
      success: "success",
    },
  },
  otpVerification: {
    title: "Verification Code",
    message: "We have sent the verification code to your email address.",
    invalidOtp: "Invalid OTP. Please try again.",
    resendTimer: "Resend OTP in",
    seconds: "seconds",
    didNotReceive: "Didn't receive code?",
    resend: "Resend",
    confirm: "Confirm",
  },
  register: {
    title: "Registration",
    usernameLabel: "Username",
    mobileLabel: "Mobile Number",
    submitButton: "Register",
    agreementText: "By creating this account, you agree to our",
    success: "Registration successfully!",
    failed: "Registration failed",
    error: "An error occurred during registration",
    emailExists: "Email already exists",
    mobileInvalid:
      "Please enter a valid 10-digit mobile number starting with 6,7,8 or 9",
  },
  resetPassword: {
    title: "Reset Password",
    instruction:
      "Please enter your new password and confirm it to reset your password",
    newPasswordLabel: "New Password",
    confirmPasswordLabel: "Confirm New Password",
    submitButton: "Reset Password",
    successMessage: "Password reset successfully!",
    passwordMismatch: "Passwords do not match",
    confirmPasswordRequired: "Please confirm your password",
    processing: "Processing...",
  },
  login: {
    title: "Log in",
    newUser: "New user?",
    registerNow: "Register Now",
    continueWithGoogle: "Continue with Google",
    or: "or",
    emailLabel: "Username or Email",
    passwordLabel: "Password",
    rememberMe: "Remember me",
    forgotPassword: "Forgot Password?",
    signIn: "Sign In",
    agreementText: "By logging in, you agree to our",
    privacyPolicy: "Privacy Policy",
    and: "and",
    cookiePolicy: "Cookie Policy",
    invalidEmail: "invalid email or password",
    passwordMinLength: "Password must be at least 6 characters",
    passwordMaxLength: "Password must be less than 10 characters",
    formErrors: "Please fix the errors in the form",
    success: "Login  successfully!",
    invalidCredentials: "Invalid credentials",
    failed: "Login failed. Please try again.",
    enterEmail: "Please enter your email",
    validEmail: "Please enter a valid email address",
    emailNotFound:
      "Email not found. Please check your email or register first.",
    emailCheckError:
      "An error occurred while checking your email. Please try again.",
  },
};
